name: "Build AppImage"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -f packaging/docker/Dockerfile -t gogstash-builder .
